version : '3'

services:
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_challenge
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  laravel:
    container_name: dev_backend
    image: dev_backend
    build:
      context: ./backend
    ports:
      - 8000:8000

  vue:
    container_name: dev_frontend
    image: dev_frontend
    build:
      context: ./frontend
    ports:
      - 80:8080